# Generated by Django 4.2.4 on 2023-08-16 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='articulos/'),
            preserve_default=False,
        ),
    ]
